# Generated by Django 6.1.2 on 2026-10-07 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('completed_games', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('total_time_spent', models.PositiveIntegerField(db_index=True, default=0)),
                ('average_time', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(db_index=True, default=0.0)),
                ('rank', models.PositiveIntegerField(db_index=True, default=1)),
                ('group_rank', models.PositiveIntegerField(default=1)),
                ('finished_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_score', 'total_time_spent', '-accuracy', 'finished_at', 'id'],
            },
        ),
    ]
