# Generated by Django 6.1.2 on 2026-10-07 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboard', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboard_entries', to='users.group'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['-total_score', 'total_time_spent', '-accuracy', 'finished_at'], name='leaderboard_total_s_a85756_idx'),
        ),
    ]
