# Generated by Django 6.1.2 on 2026-10-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.JSONField()),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.FloatField(default=0.0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('game_type', models.CharField(choices=[('quiz', 'Tezkor viktorina'), ('crossword', 'Krossvord'), ('word_search', 'So‘z qidiruv'), ('scramble', 'Harflar bo‘shliqtirmasi'), ('process_chain', 'Jarayon zanjiri'), ('matching', 'Tushuncha — ta’rif bog‘lash'), ('bingo', 'Bingo'), ('diagram', 'Chizmadan qidiruv')], max_length=30)),
                ('duration_seconds', models.PositiveIntegerField(default=300)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('icon_name', models.CharField(default='Gamepad2', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Boshlanmagan'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan'), ('time_expired', 'Vaqt tugagan'), ('violation', 'Qoidabuzildi')], db_index=True, default='in_progress', max_length=25)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('violation_count', models.PositiveSmallIntegerField(default=0)),
                ('session_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['game__order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(default='multiple_choice', max_length=50)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('correct_answer', models.JSONField()),
                ('points', models.PositiveIntegerField(default=10)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_index=True, default='Medium', max_length=20)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['game__order', 'id'],
            },
        ),
    ]
